pipeline {
  agent any

  environment {
    PROJECT          = "sinuous-origin-477316-k7"
    ZONE             = "us-central1-a"
    CLUSTER          = "gke-demo-cluster"
    DEPLOYMENT_BLUE  = "nginx-deployment"
    DEPLOYMENT_GREEN = "nginx-green"
    SERVICE          = "nginx-service-ey"
    IMAGE            = "nginx:1.25.3"
    GCP_CRED_ID      = "test-k8s"
  }

  stages {
    stage('Checkout') {
      steps {
        git(
          url: 'https://github.com/rathishvarathan/EY-Assessment.git',
          branch: 'main',
          credentialsId: 'git-rathish'
        )
      }
    }

    stage('GCP Auth') {
      steps {
        withCredentials([file(credentialsId: "${GCP_CRED_ID}", variable: 'GOOGLE_CREDENTIALS')]) {
          sh """
            gcloud auth activate-service-account --key-file=$GOOGLE_CREDENTIALS
            gcloud config set project $PROJECT
            gcloud container clusters get-credentials $CLUSTER --zone $ZONE --project $PROJECT
          """
        }
      }
    }

    stage('Deploy Green') {
      steps {
        sh """
          kubectl apply -f terraform1/gke/deployment-green.yaml
          kubectl scale deployment/${DEPLOYMENT_GREEN} --replicas=2
          kubectl rollout status deployment/${DEPLOYMENT_GREEN}
        """
      }
    }

    stage('Switch Traffic to Green') {
      steps {
        sh """
          kubectl patch service ${SERVICE} -p '{"spec":{"selector":{"app":"nginx","version":"green"}}}'
        """
      }
    }

    stage('Scale Down Blue (if exists)') {
      steps {
        sh """
        if kubectl get deployment/${DEPLOYMENT_BLUE} > /dev/null 2>&1; then
          echo "Scaling down ${DEPLOYMENT_BLUE}..."
          kubectl scale deployment/${DEPLOYMENT_BLUE} --replicas=0
        else
          echo "No blue deployment found. Skipping scale down."
        fi
        """
      }
    }
  }

  post {
    success {
      echo "Blue-Green Deployment Successful"
    }
    failure {
      echo "Deployment failed. Rolling back to blue."
      sh """
      kubectl patch service ${SERVICE} -p '{"spec":{"selector":{"app":"nginx","version":"blue"}}}'
      """
    }
  }
}
